In [2]:
import pandas as pd
import numpy as np
import os

In [25]:
files = os.listdir('c:/Users/bitcamp/Desktop/final_data/DB/재무+주가_511/')
files

['000040.csv',
 '000050.csv',
 '000080.csv',
 '000100.csv',
 '000120.csv',
 '000150.csv',
 '000180.csv',
 '000210.csv',
 '000230.csv',
 '000240.csv',
 '000270.csv',
 '000300.csv',
 '000320.csv',
 '000390.csv',
 '000430.csv',
 '000480.csv',
 '000490.csv',
 '000500.csv',
 '000520.csv',
 '000590.csv',
 '000640.csv',
 '000660.csv',
 '000670.csv',
 '000680.csv',
 '000700.csv',
 '000720.csv',
 '000850.csv',
 '000860.csv',
 '000880.csv',
 '000890.csv',
 '000910.csv',
 '000950.csv',
 '000990.csv',
 '001020.csv',
 '001040.csv',
 '001060.csv',
 '001070.csv',
 '001120.csv',
 '001130.csv',
 '001210.csv',
 '001230.csv',
 '001250.csv',
 '001260.csv',
 '001380.csv',
 '001390.csv',
 '001430.csv',
 '001440.csv',
 '001460.csv',
 '001470.csv',
 '001520.csv',
 '001530.csv',
 '001560.csv',
 '001570.csv',
 '001620.csv',
 '001630.csv',
 '001740.csv',
 '001780.csv',
 '001790.csv',
 '001800.csv',
 '001820.csv',
 '001940.csv',
 '002020.csv',
 '002030.csv',
 '002070.csv',
 '002100.csv',
 '002140.csv',
 '002150.csv',
 '002170.csv',
 '002200.csv',
 '002220.csv',
 '002240.csv',
 '002310.csv',
 '002320.csv',
 '002350.csv',
 '002390.csv',
 '002410.csv',
 '002450.csv',
 '002620.csv',
 '002710.csv',
 '002720.csv',
 '002790.csv',
 '002810.csv',
 '002820.csv',
 '002840.csv',
 '002870.csv',
 '002880.csv',
 '002900.csv',
 '002920.csv',
 '002990.csv',
 '003000.csv',
 '003010.csv',
 '003030.csv',
 '003060.csv',
 '003090.csv',
 '003160.csv',
 '003200.csv',
 '003220.csv',
 '003230.csv',
 '003240.csv',
 '003280.csv',
 '003300.csv',
 '003410.csv',
 '003480.csv',
 '003490.csv',
 '003550.csv',
 '003560.csv',
 '003570.csv',
 '003620.csv',
 '003670.csv',
 '003720.csv',
 '003780.csv',
 '003850.csv',
 '003920.csv',
 '003960.csv',
 '004000.csv',
 '004020.csv',
 '004060.csv',
 '004080.csv',
 '004090.csv',
 '004100.csv',
 '004140.csv',
 '004150.csv',
 '004170.csv',
 '004250.csv',
 '004270.csv',
 '004360.csv',
 '004370.csv',
 '004430.csv',
 '004490.csv',
 '004540.csv',
 '004560.csv',
 '004690.csv',
 '004710.csv',
 '004720.csv',
 '004770.csv',
 '004800.csv',
 '004830.csv',
 '004840.csv',
 '004870.csv',
 '004890.csv',
 '004910.csv',
 '004920.csv',
 '004960.csv',
 '004970.csv',
 '004980.csv',
 '005010.csv',
 '005090.csv',
 '005250.csv',
 '005300.csv',
 '005320.csv',
 '005360.csv',
 '005380.csv',
 '005430.csv',
 '005440.csv',
 '005490.csv',
 '005610.csv',
 '005680.csv',
 '005720.csv',
 '005740.csv',
 '005750.csv',
 '005800.csv',
 '005810.csv',
 '005820.csv',
 '005850.csv',
 '005880.csv',
 '005930.csv',
 '005950.csv',
 '005960.csv',
 '006040.csv',
 '006060.csv',
 '006120.csv',
 '006200.csv',
 '006260.csv',
 '006280.csv',
 '006340.csv',
 '006360.csv',
 '006400.csv',
 '006490.csv',
 '006570.csv',
 '006650.csv',
 '006660.csv',
 '006840.csv',
 '006880.csv',
 '006890.csv',
 '006980.csv',
 '007070.csv',
 '007120.csv',
 '007160.csv',
 '007210.csv',
 '007310.csv',
 '007340.csv',
 '007460.csv',
 '007540.csv',
 '007570.csv',
 '007590.csv',
 '007610.csv',
 '007660.csv',
 '007690.csv',
 '007700.csv',
 '007810.csv',
 '007860.csv',
 '007980.csv',
 '008040.csv',
 '008250.csv',
 '008490.csv',
 '008500.csv',
 '008770.csv',
 '008930.csv',
 '008970.csv',
 '009070.csv',
 '009140.csv',
 '009150.csv',
 '009160.csv',
 '009180.csv',
 '009200.csv',
 '009270.csv',
 '009290.csv',
 '009310.csv',
 '009410.csv',
 '009420.csv',
 '009440.csv',
 '009450.csv',
 '009470.csv',
 '009540.csv',
 '009580.csv',
 '009680.csv',
 '009810.csv',
 '009830.csv',
 '009970.csv',
 '010060.csv',
 '010100.csv',
 '010120.csv',
 '010130.csv',
 '010140.csv',
 '010600.csv',
 '010620.csv',
 '010690.csv',
 '010770.csv',
 '010780.csv',
 '010950.csv',
 '010960.csv',
 '011000.csv',
 '011070.csv',
 '011090.csv',
 '011170.csv',
 '011200.csv',
 '011210.csv',
 '011230.csv',
 '011280.csv',
 '011300.csv',
 '011330.csv',
 '011390.csv',
 '011690.csv',
 '011700.csv',
 '011760.csv',
 '011780.csv',
 '011790.csv',
 '011810.csv',
 '011930.csv',
 '012030.csv',
 '012160.csv',
 '012170.csv',
 '012200.csv',
 '012330.csv',
 '012450.csv',
 '012510.csv',
 '012600.csv',
 '012610.csv',
 '012630.csv',
 '012750.csv',
 '012800.csv',
 '013000.csv',
 '013360.csv',
 '013520.csv',
 '013570.csv',
 '013580.csv',
 '013870.csv',
 '014130.csv',
 '014280.csv',
 '014440.csv',
 '014530.csv',
 '014580.csv',
 '014680.csv',
 '014820.csv',
 '014830.csv',
 '014910.csv',
 '014990.csv',
 '015230.csv',
 '015260.csv',
 '015360.csv',
 '015540.csv',
 '015760.csv',
 '015890.csv',
 '016380.csv',
 '016450.csv',
 '016590.csv',
 '016710.csv',
 '016880.csv',
 '017040.csv',
 '017180.csv',
 '017370.csv',
 '017390.csv',
 '017550.csv',
 '017670.csv',
 '017800.csv',
 '017810.csv',
 '017900.csv',
 '017940.csv',
 '017960.csv',
 '018260.csv',
 '018670.csv',
 '018880.csv',
 '019170.csv',
 '019180.csv',
 '019440.csv',
 '019680.csv',
 '020000.csv',
 '020150.csv',
 '020560.csv',
 '021050.csv',
 '021240.csv',
 '023150.csv',
 '023530.csv',
 '023590.csv',
 '023800.csv',
 '023810.csv',
 '024070.csv',
 '024720.csv',
 '024890.csv',
 '024900.csv',
 '025000.csv',
 '025530.csv',
 '025540.csv',
 '025560.csv',
 '025620.csv',
 '025750.csv',
 '026960.csv',
 '027410.csv',
 '027740.csv',
 '028050.csv',
 '028100.csv',
 '028260.csv',
 '028670.csv',
 '029460.csv',
 '029530.csv',
 '030000.csv',
 '030200.csv',
 '030720.csv',
 '030790.csv',
 '031430.csv',
 '031440.csv',
 '031820.csv',
 '032350.csv',
 '032560.csv',
 '032640.csv',
 '033180.csv',
 '033240.csv',
 '033530.csv',
 '033780.csv',
 '033920.csv',
 '034020.csv',
 '034120.csv',
 '034220.csv',
 '034310.csv',
 '034730.csv',
 '035000.csv',
 '035150.csv',
 '035250.csv',
 '035420.csv',
 '035720.csv',
 '036420.csv',
 '036460.csv',
 '036530.csv',
 '036570.csv',
 '036580.csv',
 '037270.csv',
 '039130.csv',
 '039570.csv',
 '041650.csv',
 '042660.csv',
 '042670.csv',
 '042700.csv',
 '044380.csv',
 '044450.csv',
 '044820.csv',
 '047040.csv',
 '047050.csv',
 '047400.csv',
 '047810.csv',
 '049770.csv',
 '049800.csv',
 '051600.csv',
 '051900.csv',
 '051910.csv',
 '053210.csv',
 '053690.csv',
 '057050.csv',
 '058430.csv',
 '058650.csv',
 '058730.csv',
 '058850.csv',
 '060980.csv',
 '064350.csv',
 '064960.csv',
 '066570.csv',
 '067830.csv',
 '068270.csv',
 '068290.csv',
 '068400.csv',
 '069260.csv',
 '069620.csv',
 '069640.csv',
 '069960.csv',
 '071090.csv',
 '071950.csv',
 '071970.csv',
 '072130.csv',
 '072710.csv',
 '073240.csv',
 '074610.csv',
 '075180.csv',
 '075580.csv',
 '077500.csv',
 '077970.csv',
 '078000.csv',
 '078520.csv',
 '079160.csv',
 '079430.csv',
 '079550.csv',
 '081000.csv',
 '081660.csv',
 '082740.csv',
 '084010.csv',
 '084670.csv',
 '084690.csv',
 '085310.csv',
 '086280.csv',
 '088790.csv',
 '089470.csv',
 '089590.csv',
 '090080.csv',
 '090350.csv',
 '090370.csv',
 '090430.csv',
 '091090.csv',
 '092200.csv',
 '092220.csv',
 '092230.csv',
 '093050.csv',
 '093370.csv',
 '094280.csv',
 '095570.csv',
 '095720.csv',
 '096760.csv',
 '096770.csv',
 '097230.csv',
 '097520.csv',
 '097950.csv',
 '100220.csv',
 '100250.csv',
 '101530.csv',
 '102260.csv',
 '102280.csv',
 '102460.csv',
 '103590.csv',
 '105630.csv',
 '105840.csv',
 '108670.csv',
 '109070.csv',
 '111770.csv',
 '112610.csv',
 '115390.csv',
 '119650.csv',
 '120110.csv',
 '122900.csv',
 '123690.csv',
 '123700.csv',
 '126560.csv',
 '128820.csv',
 '128940.csv',
 '129260.csv',
 '130660.csv',
 '136490.csv',
 '138490.csv',
 '139480.csv',
 '145210.csv',
 '145990.csv',
 '155660.csv',
 '155900.csv',
 '161000.csv',
 '161390.csv',
 '163560.csv',
 '170900.csv',
 '180640.csv',
 '183190.csv',
 '185750.csv',
 '192080.csv',
 '192400.csv',
 '192820.csv',
 '194370.csv',
 '200880.csv',
 '204320.csv',
 '210540.csv',
 '210980.csv',
 '213500.csv',
 '214320.csv',
 '214330.csv',
 '214420.csv',
 '226320.csv',
 '227840.csv',
 '900140.csv']

In [5]:
df = pd.read_csv('c:/Users/bitcamp/Desktop/final_data/DB/재무+주가_511_last/000120.csv', index_col=0)
df

,date,시가,고가,저가,종가,거래량,거래대금,등락률,종목명,시가총액,...,유동부채,비유동부채,부채총계,이익잉여금,자본총계,매출액,영업이익,법인세차감전 순이익,당기순이익,자본금
0,2016-01-04,189000,190500,185000,185000,31606,5883434000,-3.14,120,4220283640000,...,1.626482e+12,8.176310e+11,2.444113e+12,5.091539e+11,2.621821e+12,1.445216e+12,5.322637e+10,2.852063e+10,2.632061e+10,NaN
1,2016-01-05,185000,201000,183500,200000,101763,19640862000,8.11,120,4562468800000,...,1.626482e+12,8.176310e+11,2.444113e+12,5.091539e+11,2.621821e+12,1.445216e+12,5.322637e+10,2.852063e+10,2.632061e+10,NaN
2,2016-01-06,200500,209000,200500,204500,63583,12996296500,2.25,120,4665124348000,...,1.626482e+12,8.176310e+11,2.444113e+12,5.091539e+11,2.621821e+12,1.445216e+12,5.322637e+10,2.852063e+10,2.632061e+10,NaN
3,2016-01-07,203500,203500,196500,197500,52582,10483729000,-3.42,120,4505437940000,...,1.626482e+12,8.176310e+11,2.444113e+12,5.091539e+11,2.621821e+12,1.445216e+12,5.322637e+10,2.852063e+10,2.632061e+10,NaN
4,2016-01-08,199500,202000,195000,201500,35066,7002846500,2.03,120,4596687316000,...,1.626482e+12,8.176310e+11,2.444113e+12,5.091539e+11,2.621821e+12,1.445216e+12,5.322637e+10,2.852063e+10,2.632061e+10,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1529,2022-03-25,132000,132000,127000,127500,58671,7559389000,-3.41,120,2908573860000,...,2.505209e+12,2.572851e+12,5.078060e+12,7.701912e+11,4.030481e+12,2.856953e+12,7.566161e+10,4.747712e+10,3.153153e+10,1.140617e+11
1530,2022-03-28,127000,130500,126000,130000,27455,3540703500,1.96,120,2965604720000,...,2.505209e+12,2.572851e+12,5.078060e+12,7.701912e+11,4.030481e+12,2.856953e+12,7.566161e+10,4.747712e+10,3.153153e+10,1.140617e+11
1531,2022-03-29,131000,131500,129000,130500,33944,4414571000,0.38,120,2977010892000,...,2.505209e+12,2.572851e+12,5.078060e+12,7.701912e+11,4.030481e+12,2.856953e+12,7.566161e+10,4.747712e+10,3.153153e+10,1.140617e+11
1532,2022-03-30,131500,131500,130500,131000,22188,2901850500,0.38,120,2988417064000,...,2.505209e+12,2.572851e+12,5.078060e+12,7.701912e+11,4.030481e+12,2.856953e+12,7.566161e+10,4.747712e+10,3.153153e+10,1.140617e+11
1533,2022-03-31,131500,132000,128000,129500,38131,4930677500,-1.15,120,2954198548000,...,2.505209e+12,2.572851e+12,5.078060e+12,7.701912e+11,4.030481e+12,2.856953e+12,7.566161e+10,4.747712e+10,3.153153e+10,1.140617e+11

In [10]:
df.isna().sum().sum()

368

In [26]:
for file in files:
    df = pd.read_csv(f'c:/Users/bitcamp/Desktop/final_data/DB/재무+주가_511_last/{file}', index_col=0)
    nan = df.isna().sum().sum()
    print(file[:7]+' : '+str(nan))

000040. : 0
000050. : 368
000080. : 0
000100. : 1534
000120. : 368
000150. : 0
000180. : 368
000210. : 736
000230. : 736
000240. : 736
000270. : 1717
000300. : 0
000320. : 368
000390. : 0
000430. : 368
000480. : 368
000490. : 0
000500. : 736
000520. : 368
000590. : 736
000640. : 428
000660. : 368
000670. : 368
000680. : 0
000700. : 0
000720. : 736
000850. : 0
000860. : 368
000880. : 736
000890. : 0
000910. : 368
000950. : 0
000990. : 0
001020. : 0
001040. : 0
001060. : 368
001070. : 368
001120. : 368
001130. : 368
001210. : 0
001230. : 0
001250. : 368
001260. : 736
001380. : 368
001390. : 368
001430. : 368
001440. : 736
001460. : 0
001470. : 0
001520. : 0
001530. : 368
001560. : 736
001570. : 368
001620. : 368
001630. : 736
001740. : 736
001780. : 368
001790. : 60
001800. : 0
001820. : 736
001940. : 0
002020. : 0
002030. : 0
002070. : 368
002100. : 368
002140. : 0
002150. : 4784
002170. : 0
002200. : 736
002220. : 0
002240. : 736
002310. : 736
002320. : 0
002350. : 368
002390. : 1534
002410. : 368
002450. : 368
002620. : 2564
002710. : 736
002720. : 368
002790. : 368
002810. : 368
002820. : 368
002840. : 0
002870. : 368
002880. : 366
002900. : 796
002920. : 368
002990. : 368
003000. : 0
003010. : 368
003030. : 736
003060. : 368
003090. : 736
003160. : 736
003200. : 0
003220. : 0
003230. : 368
003240. : 368
003280. : 368
003300. : 0
003410. : 0
003480. : 0
003490. : 0
003550. : 736
003560. : 736
003570. : 0
003620. : 736
003670. : 736
003720. : 736
003780. : 0
003850. : 3442
003920. : 736
003960. : 0
004000. : 368
004020. : 736
004060. : 368
004080. : 368
004090. : 0
004100. : 0
004140. : 368
004150. : 368
004170. : 736
004250. : 736
004270. : 0
004360. : 120
004370. : 368
004430. : 368
004490. : 368
004540. : 0
004560. : 368
004690. : 368
004710. : 0
004720. : 736
004770. : 0
004800. : 0
004830. : 0
004840. : 550
004870. : 0
004890. : 0
004910. : 0
004920. : 368
004960. : 0
004970. : 0
004980. : 0
005010. : 0
005090. : 0
005250. : 368
005300. : 368
005320. : 796
005360. : 368
005380. : 736
005430. : 736
005440. : 0
005490. : 736
005610. : 736
005680. : 121
005720. : 0
005740. : 0
005750. : 368
005800. : 60
005810. : 736
005820. : 0
005850. : 366
005880. : 368
005930. : 368
005950. : 366
005960. : 736
006040. : 736
006060. : 736
006120. : 0
006200. : 368
006260. : 864
006280. : 368
006340. : 0
006360. : 736
006400. : 0
006490. : 736
006570. : 0
006650. : 736
006660. : 368
006840. : 736
006880. : 0
006890. : 368
006980. : 368
007070. : 736
007120. : 489
007160. : 736
007210. : 0
007310. : 0
007340. : 0
007460. : 5616
007540. : 0
007570. : 368
007590. : 368
007610. : 0
007660. : 0
007690. : 368
007700. : 0
007810. : 736
007860. : 736
007980. : 0
008040. : 0
008250. : 121
008490. : 736
008500. : 1534
008770. : 368
008930. : 616
008970. : 368
009070. : 736
009140. : 368
009150. : 736
009160. : 368
009180. : 614
009200. : 0
009270. : 368
009290. : 368
009310. : 736
009410. : 736
009420. : 368
009440. : 736
009450. : 736
009470. : 368
009540. : 0
009580. : 0
009680. : 736
009810. : 0
009830. : 736
009970. : 0
010060. : 0
010100. : 0
010120. : 736
010130. : 736
010140. : 368
010600. : 0
010620. : 736
010690. : 368
010770. : 1100
010780. : 0
010950. : 60
010960. : 368
011000. : 736
011070. : 736
011090. : 0
011170. : 736
011200. : 736
011210. : 368
011230. : 0
011280. : 551
011300. : 368
011330. : 5616
011390. : 736
011690. : 0
011700. : 736
011760. : 0
011780. : 0
011790. : 0
011810. : 736
011930. : 2749
012030. : 368
012160. : 0
012170. : 0
012200. : 368
012330. : 736
012450. : 368
012510. : 368
012600. : 0
012610. : 368
012630. : 0
012750. : 736
012800. : 489
013000. : 368
013360. : 0
013520. : 368
013570. : 0
013580. : 0
013870. : 0
014130. : 0
014280. : 1902
014440. : 0
014530. : 0
014580. : 0
014680. : 736
014820. : 120
014830. : 0
014910. : 368
014990. : 736
015230. : 368
015260. : 0
015360. : 0
015540. : 0
015760. : 0
015890. : 0
016380. : 736
016450. : 551
016590. : 736
016710. : 368
016880. : 736
017040. : 0
017180. : 368
017370. : 0
017390. : 736
017550. : 736
017670. : 368
017800. : 736
017810. : 736
017900. : 736
017940. : 736
017960. : 0
018260. : 0
018670. : 736
018880. : 0
019170. : 368
019180. : 551
019440. : 368
019680. : 736
020000. : 736
020150. : 0
020560. : 368
021050. : 0
021240. : 368
023150. : 0
023530. : 736
023590. : 183
023800. : 0
023810. : 368
024070. : 368
024720. : 0
024890. : 0
024900. : 0
025000. : 1534
025530. : 0
025540. : 368
025560. : 0
025620. : 550
025750. : 368
026960. : 0
027410. : 368
027740. : 0
028050. : 736
028100. : 368
028260. : 368
028670. : 736
029460. : 368
029530. : 0
030000. : 736
030200. : 736
030720. : 736
030790. : 368
031430. : 368
031440. : 0
031820. : 0
032350. : 368
032560. : 368
032640. : 917
033180. : 368
033240. : 0
033530. : 0
033780. : 0
033920. : 736
034020. : 368
034120. : 0
034220. : 368
034310. : 368
034730. : 736
035000. : 736
035150. : 671
035250. : 736
035420. : 368
035720. : 736
036420. : 736
036460. : 0
036530. : 0
036570. : 736
036580. : 736
037270. : 736
039130. : 368
039570. : 368
041650. : 368
042660. : 736
042670. : 0
042700. : 368
044380. : 2564
044450. : 0
044820. : 736
047040. : 368
047050. : 736
047400. : 368
047810. : 0
049770. : 736
049800. : 0
051600. : 368
051900. : 368
051910. : 736
053210. : 368
053690. : 0
057050. : 736
058430. : 368
058650. : 736
058730. : 0
058850. : 368
060980. : 736
064350. : 0
064960. : 0
066570. : 736
067830. : 0
068270. : 0
068290. : 368
068400. : 917
069260. : 368
069620. : 736
069640. : 736
069960. : 0
071090. : 5616
071950. : 368
071970. : 0
072130. : 368
072710. : 368
073240. : 368
074610. : 0
075180. : 736
075580. : 0
077500. : 368
077970. : 2749
078000. : 368
078520. : 0
079160. : 368
079430. : 308
079550. : 0
081000. : 368
081660. : 0
082740. : 736
084010. : 0
084670. : 0
084690. : 368
085310. : 1534
086280. : 736
088790. : 736
089470. : 368
089590. : 2564
090080. : 368
090350. : 368
090370. : 0
090430. : 368
091090. : 0
092200. : 736
092220. : 368
092230. : 736
093050. : 736
093370. : 0
094280. : 0
095570. : 368
095720. : 0
096760. : 736
096770. : 368
097230. : 368
097520. : 736
097950. : 736
100220. : 368
100250. : 0
101530. : 504
102260. : 368
102280. : 368
102460. : 4912
103590. : 368
105630. : 0
105840. : 0
108670. : 0
109070. : 2749
111770. : 0
112610. : 368
115390. : 0
119650. : 736
120110. : 736
122900. : 736
123690. : 736
123700. : 0
126560. : 368
128820. : 428
128940. : 736
129260. : 0
130660. : 736
136490. : 736
138490. : 0
139480. : 0
145210. : 366
145990. : 736
155660. : 368
155900. : 9572
161000. : 368
161390. : 736
163560. : 550
170900. : 368
180640. : 368
183190. : 0
185750. : 5616
192080. : 780
192400. : 368
192820. : 736
194370. : 826
200880. : 368
204320. : 3068
210540. : 0
210980. : 736
213500. : 736
214320. : 736
214330. : 736
214420. : 0
226320. : 368
227840. : 2564
900140. : 9940

In [15]:
ya_df = pd.read_csv('c:/Users/bitcamp/Desktop/final_data/DB/재무+주가_511_last/102460.csv', index_col=0)
ya_df.isna().sum()

date            0
시가              0
고가              0
저가              0
종가              0
거래량             0
거래대금            0
등락률             0
종목명             0
시가총액            0
상장주식수           0
수정종가            0
BPS             0
PER             0
PBR             0
EPS             0
DIV             0
DPS             0
month           0
quarter         0
유동자산          368
비유동자산         368
자산총계          368
유동부채          368
비유동부채         368
부채총계          368
이익잉여금         432
자본총계          368
매출액           368
영업이익          368
법인세차감전 순이익    368
당기순이익         368
자본금           432
dtype: int64

In [16]:
ya_df

,date,시가,고가,저가,종가,거래량,거래대금,등락률,종목명,시가총액,...,유동부채,비유동부채,부채총계,이익잉여금,자본총계,매출액,영업이익,법인세차감전 순이익,당기순이익,자본금
0,2016-01-04,38900,39150,37050,37450,69107,2637699100,-1.19,102460,483105000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-01-05,36200,38200,36200,38000,61569,2288818150,1.47,102460,490200000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-01-06,38300,39400,37550,39400,112540,4362017350,3.68,102460,508260000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-01-07,39400,39850,37700,38300,57219,2203780350,-2.79,102460,494070000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-01-08,37000,39550,36400,39150,95534,3638190950,2.22,102460,505035000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1529,2022-03-25,29550,30300,29050,29750,70835,2105697100,1.19,102460,535457665750,...,4.808644e+10,1.856017e+11,2.336881e+11,1.996122e+11,2.425901e+11,3.716245e+10,2.957960e+09,2.587983e+09,1.894450e+09,9.249288e+09
1530,2022-03-28,30100,30250,29000,29000,54983,1610502550,-2.52,102460,521958733000,...,4.808644e+10,1.856017e+11,2.336881e+11,1.996122e+11,2.425901e+11,3.716245e+10,2.957960e+09,2.587983e+09,1.894450e+09,9.249288e+09
1531,2022-03-29,29050,29300,28850,29050,26124,758794550,0.17,102460,522858661850,...,4.808644e+10,1.856017e+11,2.336881e+11,1.996122e+11,2.425901e+11,3.716245e+10,2.957960e+09,2.587983e+09,1.894450e+09,9.249288e+09
1532,2022-03-30,29200,31200,29200,29500,201472,6095947350,1.55,102460,530958021500,...,4.808644e+10,1.856017e+11,2.336881e+11,1.996122e+11,2.425901e+11,3.716245e+10,2.957960e+09,2.587983e+09,1.894450e+09,9.249288e+09
1533,2022-03-31,29500,30550,29500,29900,92703,2793363750,1.36,102460,538157452300,...,4.808644e+10,1.856017e+11,2.336881e+11,1.996122e+11,2.425901e+11,3.716245e+10,2.957960e+09,2.587983e+09,1.894450e+09,9.249288e+09

In [24]:
ya_df[360:400]

,date,시가,고가,저가,종가,거래량,거래대금,등락률,종목명,시가총액,...,유동부채,비유동부채,부채총계,이익잉여금,자본총계,매출액,영업이익,법인세차감전 순이익,당기순이익,자본금
360,2017-06-21,30400,30400,29700,29700,7032,209636000,-2.14,102460,383130000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
361,2017-06-22,29750,30150,29650,29900,12234,365886000,0.67,102460,385710000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
362,2017-06-23,30250,30250,29550,29550,11545,343778900,-1.17,102460,381195000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
363,2017-06-26,29950,29950,28800,28900,10663,309965300,-2.20,102460,372810000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
364,2017-06-27,28900,29400,28500,28800,9682,279073300,-0.35,102460,371520000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
365,2017-06-28,28550,28950,28400,28500,9756,278414200,-1.04,102460,367650000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
366,2017-06-29,28600,28950,28500,28900,4817,138396250,1.40,102460,372810000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
367,2017-06-30,28900,28950,28600,28750,5240,150590300,-0.52,102460,370875000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
368,2017-07-03,28550,28650,28350,28550,6372,181748500,-0.70,102460,368295000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
369,2017-07-04,28300,28750,28300,28400,5213,148813750,-0.53,102460,366360000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
370,2017-07-05,28200,28600,28200,28200,7171,203231200,-0.70,102460,363780000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
371,2017-07-06,28750,29300,28350,28550,7669,219977850,1.24,102460,368295000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
372,2017-07-07,28450,28950,28450,28600,5506,157437200,0.18,102460,368940000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
373,2017-07-10,28700,28700,28250,28450,5480,155347750,-0.52,102460,367005000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
374,2017-07-11,28750,28750,28200,28500,5013,141808650,0.18,102460,367650000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
375,2017-07-12,28500,28500,28000,28100,11220,315663300,-1.40,102460,362490000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
376,2017-07-13,28100,28250,27500,27850,14832,410767450,-0.89,102460,359265000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
377,2017-07-14,27950,27950,27100,27700,26292,717459450,-0.54,102460,357330000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
378,2017-07-17,27600,28100,27600,27800,7358,204982650,0.36,102460,358620000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
379,2017-07-18,27550,28000,27150,27400,18965,518491850,-1.44,102460,353460000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
380,2017-07-19,27450,27500,27000,27400,12138,329850750,0.00,102460,353460000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
381,2017-07-20,27650,27650,27250,27500,4172,114166650,0.36,102460,354750000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
382,2017-07-21,27550,27950,27550,27850,6004,166917200,1.27,102460,359265000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
383,2017-07-24,27850,27900,27200,27500,12658,347994550,-1.26,102460,354750000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
384,2017-07-25,27700,27700,27100,27150,10796,294586750,-1.27,102460,350235000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
385,2017-07-26,27150,27700,27150,27400,5878,161356450,0.92,102460,353460000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
386,2017-07-27,27400,27650,27300,27600,8635,236939800,0.73,102460,356040000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
387,2017-07-28,27850,27850,27200,27200,12065,331761650,-1.45,102460,350880000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
388,2017-07-31,27450,27550,27050,27550,6591,180035400,1.29,102460,355395000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
389,2017-08-01,27550,27750,27500,27500,11577,318768050,-0.18,102460,354750000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
390,2017-08-02,27550,28050,27500,27850,8769,243597800,1.27,102460,359265000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
391,2017-08-03,27750,28100,27400,27550,12285,340397000,-1.08,102460,355395000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
392,2017-08-04,28050,28050,27500,27600,5507,152310200,0.18,102460,356040000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
393,2017-08-07,27400,27950,27400,27900,7374,203819050,1.09,102460,359910000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
394,2017-08-08,27950,28000,27600,27700,2873,79798200,-0.72,102460,357330000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
395,2017-08-09,28000,28000,27300,27350,5161,141803050,-1.26,102460,352815000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
396,2017-08-10,27150,27650,27000,27550,7071,193028650,0.73,102460,355395000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
397,2017-08-11,27300,27500,26850,26900,9214,249242200,-2.36,102460,347010000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
398,2017-08-14,27350,27450,27000,27200,5617,152852800,1.12,102460,350880000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN
399,2017-08-16,27250,27600,27050,27200,3995,108980650,0.00,102460,350880000000,...,1.914324e+10,4.870909e+10,6.785232e+10,NaN,2.115271e+11,3.179618e+10,4.391952e+09,4.424642e+09,3.499438e+09,NaN

In [27]:
len(files)

511

# 511리스트 만들기

In [36]:
stock_codes = []
for file in files:
    stock_codes.append(file[:6])
stock_codes

['000040',
 '000050',
 '000080',
 '000100',
 '000120',
 '000150',
 '000180',
 '000210',
 '000230',
 '000240',
 '000270',
 '000300',
 '000320',
 '000390',
 '000430',
 '000480',
 '000490',
 '000500',
 '000520',
 '000590',
 '000640',
 '000660',
 '000670',
 '000680',
 '000700',
 '000720',
 '000850',
 '000860',
 '000880',
 '000890',
 '000910',
 '000950',
 '000990',
 '001020',
 '001040',
 '001060',
 '001070',
 '001120',
 '001130',
 '001210',
 '001230',
 '001250',
 '001260',
 '001380',
 '001390',
 '001430',
 '001440',
 '001460',
 '001470',
 '001520',
 '001530',
 '001560',
 '001570',
 '001620',
 '001630',
 '001740',
 '001780',
 '001790',
 '001800',
 '001820',
 '001940',
 '002020',
 '002030',
 '002070',
 '002100',
 '002140',
 '002150',
 '002170',
 '002200',
 '002220',
 '002240',
 '002310',
 '002320',
 '002350',
 '002390',
 '002410',
 '002450',
 '002620',
 '002710',
 '002720',
 '002790',
 '002810',
 '002820',
 '002840',
 '002870',
 '002880',
 '002900',
 '002920',
 '002990',
 '003000',
 '003010',
 '003030',
 '003060',
 '003090',
 '003160',
 '003200',
 '003220',
 '003230',
 '003240',
 '003280',
 '003300',
 '003410',
 '003480',
 '003490',
 '003550',
 '003560',
 '003570',
 '003620',
 '003670',
 '003720',
 '003780',
 '003850',
 '003920',
 '003960',
 '004000',
 '004020',
 '004060',
 '004080',
 '004090',
 '004100',
 '004140',
 '004150',
 '004170',
 '004250',
 '004270',
 '004360',
 '004370',
 '004430',
 '004490',
 '004540',
 '004560',
 '004690',
 '004710',
 '004720',
 '004770',
 '004800',
 '004830',
 '004840',
 '004870',
 '004890',
 '004910',
 '004920',
 '004960',
 '004970',
 '004980',
 '005010',
 '005090',
 '005250',
 '005300',
 '005320',
 '005360',
 '005380',
 '005430',
 '005440',
 '005490',
 '005610',
 '005680',
 '005720',
 '005740',
 '005750',
 '005800',
 '005810',
 '005820',
 '005850',
 '005880',
 '005930',
 '005950',
 '005960',
 '006040',
 '006060',
 '006120',
 '006200',
 '006260',
 '006280',
 '006340',
 '006360',
 '006400',
 '006490',
 '006570',
 '006650',
 '006660',
 '006840',
 '006880',
 '006890',
 '006980',
 '007070',
 '007120',
 '007160',
 '007210',
 '007310',
 '007340',
 '007460',
 '007540',
 '007570',
 '007590',
 '007610',
 '007660',
 '007690',
 '007700',
 '007810',
 '007860',
 '007980',
 '008040',
 '008250',
 '008490',
 '008500',
 '008770',
 '008930',
 '008970',
 '009070',
 '009140',
 '009150',
 '009160',
 '009180',
 '009200',
 '009270',
 '009290',
 '009310',
 '009410',
 '009420',
 '009440',
 '009450',
 '009470',
 '009540',
 '009580',
 '009680',
 '009810',
 '009830',
 '009970',
 '010060',
 '010100',
 '010120',
 '010130',
 '010140',
 '010600',
 '010620',
 '010690',
 '010770',
 '010780',
 '010950',
 '010960',
 '011000',
 '011070',
 '011090',
 '011170',
 '011200',
 '011210',
 '011230',
 '011280',
 '011300',
 '011330',
 '011390',
 '011690',
 '011700',
 '011760',
 '011780',
 '011790',
 '011810',
 '011930',
 '012030',
 '012160',
 '012170',
 '012200',
 '012330',
 '012450',
 '012510',
 '012600',
 '012610',
 '012630',
 '012750',
 '012800',
 '013000',
 '013360',
 '013520',
 '013570',
 '013580',
 '013870',
 '014130',
 '014280',
 '014440',
 '014530',
 '014580',
 '014680',
 '014820',
 '014830',
 '014910',
 '014990',
 '015230',
 '015260',
 '015360',
 '015540',
 '015760',
 '015890',
 '016380',
 '016450',
 '016590',
 '016710',
 '016880',
 '017040',
 '017180',
 '017370',
 '017390',
 '017550',
 '017670',
 '017800',
 '017810',
 '017900',
 '017940',
 '017960',
 '018260',
 '018670',
 '018880',
 '019170',
 '019180',
 '019440',
 '019680',
 '020000',
 '020150',
 '020560',
 '021050',
 '021240',
 '023150',
 '023530',
 '023590',
 '023800',
 '023810',
 '024070',
 '024720',
 '024890',
 '024900',
 '025000',
 '025530',
 '025540',
 '025560',
 '025620',
 '025750',
 '026960',
 '027410',
 '027740',
 '028050',
 '028100',
 '028260',
 '028670',
 '029460',
 '029530',
 '030000',
 '030200',
 '030720',
 '030790',
 '031430',
 '031440',
 '031820',
 '032350',
 '032560',
 '032640',
 '033180',
 '033240',
 '033530',
 '033780',
 '033920',
 '034020',
 '034120',
 '034220',
 '034310',
 '034730',
 '035000',
 '035150',
 '035250',
 '035420',
 '035720',
 '036420',
 '036460',
 '036530',
 '036570',
 '036580',
 '037270',
 '039130',
 '039570',
 '041650',
 '042660',
 '042670',
 '042700',
 '044380',
 '044450',
 '044820',
 '047040',
 '047050',
 '047400',
 '047810',
 '049770',
 '049800',
 '051600',
 '051900',
 '051910',
 '053210',
 '053690',
 '057050',
 '058430',
 '058650',
 '058730',
 '058850',
 '060980',
 '064350',
 '064960',
 '066570',
 '067830',
 '068270',
 '068290',
 '068400',
 '069260',
 '069620',
 '069640',
 '069960',
 '071090',
 '071950',
 '071970',
 '072130',
 '072710',
 '073240',
 '074610',
 '075180',
 '075580',
 '077500',
 '077970',
 '078000',
 '078520',
 '079160',
 '079430',
 '079550',
 '081000',
 '081660',
 '082740',
 '084010',
 '084670',
 '084690',
 '085310',
 '086280',
 '088790',
 '089470',
 '089590',
 '090080',
 '090350',
 '090370',
 '090430',
 '091090',
 '092200',
 '092220',
 '092230',
 '093050',
 '093370',
 '094280',
 '095570',
 '095720',
 '096760',
 '096770',
 '097230',
 '097520',
 '097950',
 '100220',
 '100250',
 '101530',
 '102260',
 '102280',
 '102460',
 '103590',
 '105630',
 '105840',
 '108670',
 '109070',
 '111770',
 '112610',
 '115390',
 '119650',
 '120110',
 '122900',
 '123690',
 '123700',
 '126560',
 '128820',
 '128940',
 '129260',
 '130660',
 '136490',
 '138490',
 '139480',
 '145210',
 '145990',
 '155660',
 '155900',
 '161000',
 '161390',
 '163560',
 '170900',
 '180640',
 '183190',
 '185750',
 '192080',
 '192400',
 '192820',
 '194370',
 '200880',
 '204320',
 '210540',
 '210980',
 '213500',
 '214320',
 '214330',
 '214420',
 '226320',
 '227840',
 '900140']

In [40]:
df = pd.DataFrame({'stock_code':stock_codes})
df

    stock_code
0       000040
1       000050
2       000080
3       000100
4       000120
..         ...
506     214330
507     214420
508     226320
509     227840
510     900140

[511 rows x 1 columns]

In [41]:
df.to_csv('c:/Users/bitcamp/Desktop/final_data/DB_list_stock_code.csv')

# 재무비율 삭제

In [44]:
stock_df = pd.read_csv('c:/Users/bitcamp/Desktop/final_data/DB/재무+주가_511_last/000040.csv', index_col=0)
stock_df.head(2)

,date,시가,고가,저가,종가,거래량,거래대금,등락률,종목명,시가총액,...,유동부채,비유동부채,부채총계,이익잉여금,자본총계,매출액,영업이익,법인세차감전 순이익,당기순이익,자본금
0,2016-01-04,1295,1325,1255,1305,6053163,7839874495,2.76,40,228776632020,...,6.620836e+10,1.466770e+10,8.087606e+10,-3.186228e+10,6.502035e+10,1.979041e+10,-2.729799e+09,-3.476061e+09,-3.476061e+09,8.765388e+10
1,2016-01-05,1285,1350,1280,1310,9674168,12787405175,0.38,40,229653170840,...,6.620836e+10,1.466770e+10,8.087606e+10,-3.186228e+10,6.502035e+10,1.979041e+10,-2.729799e+09,-3.476061e+09,-3.476061e+09,8.765388e+10

In [45]:
stock_df.columns

Index(['date', '시가', '고가', '저가', '종가', '거래량', '거래대금', '등락률', '종목명', '시가총액',
       '상장주식수', '수정종가', 'BPS', 'PER', 'PBR', 'EPS', 'DIV', 'DPS', 'month',
       'quarter', '유동자산', '비유동자산', '자산총계', '유동부채', '비유동부채', '부채총계', '이익잉여금',
       '자본총계', '매출액', '영업이익', '법인세차감전 순이익', '당기순이익', '자본금'],
      dtype='object')

In [48]:
stock_df.drop(['BPS', 'PER', 'PBR', 'EPS', 'DIV', 'DPS', 'month'], axis=1, inplace=True)

In [49]:
stock_df.columns

Index(['date', '시가', '고가', '저가', '종가', '거래량', '거래대금', '등락률', '종목명', '시가총액',
       '상장주식수', '수정종가', 'quarter', '유동자산', '비유동자산', '자산총계', '유동부채', '비유동부채',
       '부채총계', '이익잉여금', '자본총계', '매출액', '영업이익', '법인세차감전 순이익', '당기순이익', '자본금'],
      dtype='object')

In [50]:
files = os.listdir('c:/Users/bitcamp/Desktop/final_data/DB/재무+주가_511_last/')

In [51]:
for file in files:
    stock_df = pd.read_csv(f'c:/Users/bitcamp/Desktop/final_data/DB/재무+주가_511_last/{file}', index_col=0)
    stock_df.drop(['BPS', 'PER', 'PBR', 'EPS', 'DIV', 'DPS', 'month'], axis=1, inplace=True)
    stock_df.to_csv(f'c:/Users/bitcamp/Desktop/final_data/머신러닝_재무데이터/종목별_511/{file}')

# nan값 확인

In [52]:
files = os.listdir('c:/Users/bitcamp/Desktop/final_data/머신러닝_재무데이터/종목별_511/')

In [53]:
for file in files:
    df = pd.read_csv(f'c:/Users/bitcamp/Desktop/final_data/머신러닝_재무데이터/종목별_511/{file}', index_col=0)
    nan = df.isna().sum().sum()
    print(file[:7]+' : '+str(nan))

000040. : 0
000050. : 368
000080. : 0
000100. : 1534
000120. : 368
000150. : 0
000180. : 368
000210. : 736
000230. : 736
000240. : 736
000270. : 1717
000300. : 0
000320. : 368
000390. : 0
000430. : 368
000480. : 368
000490. : 0
000500. : 736
000520. : 368
000590. : 736
000640. : 428
000660. : 368
000670. : 368
000680. : 0
000700. : 0
000720. : 736
000850. : 0
000860. : 368
000880. : 736
000890. : 0
000910. : 368
000950. : 0
000990. : 0
001020. : 0
001040. : 0
001060. : 368
001070. : 368
001120. : 368
001130. : 368
001210. : 0
001230. : 0
001250. : 368
001260. : 736
001380. : 368
001390. : 368
001430. : 368
001440. : 736
001460. : 0
001470. : 0
001520. : 0
001530. : 368
001560. : 736
001570. : 368
001620. : 368
001630. : 736
001740. : 736
001780. : 368
001790. : 60
001800. : 0
001820. : 736
001940. : 0
002020. : 0
002030. : 0
002070. : 368
002100. : 368
002140. : 0
002150. : 4784
002170. : 0
002200. : 736
002220. : 0
002240. : 736
002310. : 736
002320. : 0
002350. : 368
002390. : 1534
002410. : 368
002450. : 368
002620. : 2564
002710. : 736
002720. : 368
002790. : 368
002810. : 368
002820. : 368
002840. : 0
002870. : 368
002880. : 366
002900. : 796
002920. : 368
002990. : 368
003000. : 0
003010. : 368
003030. : 736
003060. : 368
003090. : 736
003160. : 736
003200. : 0
003220. : 0
003230. : 368
003240. : 368
003280. : 368
003300. : 0
003410. : 0
003480. : 0
003490. : 0
003550. : 736
003560. : 736
003570. : 0
003620. : 736
003670. : 736
003720. : 736
003780. : 0
003850. : 3442
003920. : 736
003960. : 0
004000. : 368
004020. : 736
004060. : 368
004080. : 368
004090. : 0
004100. : 0
004140. : 368
004150. : 368
004170. : 736
004250. : 736
004270. : 0
004360. : 120
004370. : 368
004430. : 368
004490. : 368
004540. : 0
004560. : 368
004690. : 368
004710. : 0
004720. : 736
004770. : 0
004800. : 0
004830. : 0
004840. : 550
004870. : 0
004890. : 0
004910. : 0
004920. : 368
004960. : 0
004970. : 0
004980. : 0
005010. : 0
005090. : 0
005250. : 368
005300. : 368
005320. : 796
005360. : 368
005380. : 736
005430. : 736
005440. : 0
005490. : 736
005610. : 736
005680. : 121
005720. : 0
005740. : 0
005750. : 368
005800. : 60
005810. : 736
005820. : 0
005850. : 366
005880. : 368
005930. : 368
005950. : 366
005960. : 736
006040. : 736
006060. : 736
006120. : 0
006200. : 368
006260. : 864
006280. : 368
006340. : 0
006360. : 736
006400. : 0
006490. : 736
006570. : 0
006650. : 736
006660. : 368
006840. : 736
006880. : 0
006890. : 368
006980. : 368
007070. : 736
007120. : 489
007160. : 736
007210. : 0
007310. : 0
007340. : 0
007460. : 5616
007540. : 0
007570. : 368
007590. : 368
007610. : 0
007660. : 0
007690. : 368
007700. : 0
007810. : 736
007860. : 736
007980. : 0
008040. : 0
008250. : 121
008490. : 736
008500. : 1534
008770. : 368
008930. : 616
008970. : 368
009070. : 736
009140. : 368
009150. : 736
009160. : 368
009180. : 614
009200. : 0
009270. : 368
009290. : 368
009310. : 736
009410. : 736
009420. : 368
009440. : 736
009450. : 736
009470. : 368
009540. : 0
009580. : 0
009680. : 736
009810. : 0
009830. : 736
009970. : 0
010060. : 0
010100. : 0
010120. : 736
010130. : 736
010140. : 368
010600. : 0
010620. : 736
010690. : 368
010770. : 1100
010780. : 0
010950. : 60
010960. : 368
011000. : 736
011070. : 736
011090. : 0
011170. : 736
011200. : 736
011210. : 368
011230. : 0
011280. : 551
011300. : 368
011330. : 5616
011390. : 736
011690. : 0
011700. : 736
011760. : 0
011780. : 0
011790. : 0
011810. : 736
011930. : 2749
012030. : 368
012160. : 0
012170. : 0
012200. : 368
012330. : 736
012450. : 368
012510. : 368
012600. : 0
012610. : 368
012630. : 0
012750. : 736
012800. : 489
013000. : 368
013360. : 0
013520. : 368
013570. : 0
013580. : 0
013870. : 0
014130. : 0
014280. : 1902
014440. : 0
014530. : 0
014580. : 0
014680. : 736
014820. : 120
014830. : 0
014910. : 368
014990. : 736
015230. : 368
015260. : 0
015360. : 0
015540. : 0
015760. : 0
015890. : 0
016380. : 736
016450. : 551
016590. : 736
016710. : 368
016880. : 736
017040. : 0
017180. : 368
017370. : 0
017390. : 736
017550. : 736
017670. : 368
017800. : 736
017810. : 736
017900. : 736
017940. : 736
017960. : 0
018260. : 0
018670. : 736
018880. : 0
019170. : 368
019180. : 551
019440. : 368
019680. : 736
020000. : 736
020150. : 0
020560. : 368
021050. : 0
021240. : 368
023150. : 0
023530. : 736
023590. : 183
023800. : 0
023810. : 368
024070. : 368
024720. : 0
024890. : 0
024900. : 0
025000. : 1534
025530. : 0
025540. : 368
025560. : 0
025620. : 550
025750. : 368
026960. : 0
027410. : 368
027740. : 0
028050. : 736
028100. : 368
028260. : 368
028670. : 736
029460. : 368
029530. : 0
030000. : 736
030200. : 736
030720. : 736
030790. : 368
031430. : 368
031440. : 0
031820. : 0
032350. : 368
032560. : 368
032640. : 917
033180. : 368
033240. : 0
033530. : 0
033780. : 0
033920. : 736
034020. : 368
034120. : 0
034220. : 368
034310. : 368
034730. : 736
035000. : 736
035150. : 671
035250. : 736
035420. : 368
035720. : 736
036420. : 736
036460. : 0
036530. : 0
036570. : 736
036580. : 736
037270. : 736
039130. : 368
039570. : 368
041650. : 368
042660. : 736
042670. : 0
042700. : 368
044380. : 2564
044450. : 0
044820. : 736
047040. : 368
047050. : 736
047400. : 368
047810. : 0
049770. : 736
049800. : 0
051600. : 368
051900. : 368
051910. : 736
053210. : 368
053690. : 0
057050. : 736
058430. : 368
058650. : 736
058730. : 0
058850. : 368
060980. : 736
064350. : 0
064960. : 0
066570. : 736
067830. : 0
068270. : 0
068290. : 368
068400. : 917
069260. : 368
069620. : 736
069640. : 736
069960. : 0
071090. : 5616
071950. : 368
071970. : 0
072130. : 368
072710. : 368
073240. : 368
074610. : 0
075180. : 736
075580. : 0
077500. : 368
077970. : 2749
078000. : 368
078520. : 0
079160. : 368
079430. : 308
079550. : 0
081000. : 368
081660. : 0
082740. : 736
084010. : 0
084670. : 0
084690. : 368
085310. : 1534
086280. : 736
088790. : 736
089470. : 368
089590. : 2564
090080. : 368
090350. : 368
090370. : 0
090430. : 368
091090. : 0
092200. : 736
092220. : 368
092230. : 736
093050. : 736
093370. : 0
094280. : 0
095570. : 368
095720. : 0
096760. : 736
096770. : 368
097230. : 368
097520. : 736
097950. : 736
100220. : 368
100250. : 0
101530. : 504
102260. : 368
102280. : 368
102460. : 4912
103590. : 368
105630. : 0
105840. : 0
108670. : 0
109070. : 2749
111770. : 0
112610. : 368
115390. : 0
119650. : 736
120110. : 736
122900. : 736
123690. : 736
123700. : 0
126560. : 368
128820. : 428
128940. : 736
129260. : 0
130660. : 736
136490. : 736
138490. : 0
139480. : 0
145210. : 366
145990. : 736
155660. : 368
155900. : 368
161000. : 368
161390. : 736
163560. : 550
170900. : 368
180640. : 368
183190. : 0
185750. : 5616
192080. : 780
192400. : 368
192820. : 736
194370. : 826
200880. : 368
204320. : 3068
210540. : 0
210980. : 736
213500. : 736
214320. : 736
214330. : 736
214420. : 0
226320. : 368
227840. : 2564
900140. : 736

In [128]:
stock_nan_df = pd.read_csv('c:/Users/bitcamp/Desktop/final_data/머신러닝_재무데이터/종목별_511/000270.csv', index_col=0)
stock_nan_df.head(2)

,date,시가,고가,저가,종가,거래량,거래대금,등락률,종목명,시가총액,...,유동부채,비유동부채,부채총계,이익잉여금,자본총계,매출액,영업이익,법인세차감전 순이익,당기순이익,자본금
0,2016-01-04,51700,51800,50600,50800,1016680,51802223300,-3.42,270,20592458027600,...,1.636467e+13,7.321833e+12,2.368650e+13,NaN,2.459700e+13,1.264937e+13,6.336220e+11,1.046704e+12,9.445840e+11,NaN
1,2016-01-05,50100,51300,50000,50700,989919,50189461600,-0.20,270,20551921692900,...,1.636467e+13,7.321833e+12,2.368650e+13,NaN,2.459700e+13,1.264937e+13,6.336220e+11,1.046704e+12,9.445840e+11,NaN

In [129]:
stock_nan_df.isna().sum()

date             0
시가               0
고가               0
저가               0
종가               0
거래량              0
거래대금             0
등락률              0
종목명              0
시가총액             0
상장주식수            0
수정종가             0
quarter          0
유동자산             0
비유동자산            0
자산총계             0
유동부채             0
비유동부채            0
부채총계             0
이익잉여금          183
자본총계             0
매출액              0
영업이익             0
법인세차감전 순이익       0
당기순이익            0
자본금           1534
dtype: int64

# 전체 nan값 확인

In [123]:
stock_nan_df[-1:].isna().sum().sum()

1

In [125]:
for file in files:
    stock_nan_df = pd.read_csv(f'c:/Users/bitcamp/Desktop/final_data/머신러닝_재무데이터/종목별_511/{file}', index_col=0)
    if stock_nan_df[-1:].isna().sum().sum() > 0:
        print(file[:6]+' : '+str(stock_nan_df[-1:].isna().sum().sum()))

000100 : 1
000270 : 1
002390 : 1
008500 : 1
014280 : 1
025000 : 1
085310 : 1
204320 : 2

# nan값 이유 확인

In [137]:
yabal_df = pd.read_excel('c:/Users/bitcamp/Desktop/final_data/재무제표/000270.xlsx')
yabal_df.iloc[46,28:33]

20170331    23794398000000
20161231    23465759000000
20160930    22837121000000
20160630    22194359000000
20160331    21447074000000
Name: 46, dtype: object

In [171]:
nan_li = []
for file in files:
    df = pd.read_csv(f'c:/Users/bitcamp/Desktop/final_data/머신러닝_재무데이터/종목별_511/{file}', index_col=0)
    nan = df.isna().sum().sum()
    if nan > 368:
        print(file[:7]+' : '+str(nan))
        nan_li.append(nan)

000100. : 1534
000210. : 736
000230. : 736
000240. : 736
000270. : 1717
000500. : 736
000590. : 736
000640. : 428
000720. : 736
000880. : 736
001260. : 736
001440. : 736
001560. : 736
001630. : 736
001740. : 736
001820. : 736
002150. : 4784
002200. : 736
002240. : 736
002310. : 736
002390. : 1534
002620. : 2564
002710. : 736
002900. : 796
003030. : 736
003090. : 736
003160. : 736
003550. : 736
003560. : 736
003620. : 736
003670. : 736
003720. : 736
003850. : 3442
003920. : 736
004020. : 736
004170. : 736
004250. : 736
004720. : 736
004840. : 550
005320. : 796
005380. : 736
005430. : 736
005490. : 736
005610. : 736
005810. : 736
005960. : 736
006040. : 736
006060. : 736
006260. : 864
006360. : 736
006490. : 736
006650. : 736
006840. : 736
007070. : 736
007120. : 489
007160. : 736
007460. : 5616
007810. : 736
007860. : 736
008490. : 736
008500. : 1534
008930. : 616
009070. : 736
009150. : 736
009180. : 614
009310. : 736
009410. : 736
009440. : 736
009450. : 736
009680. : 736
009830. : 736
010120. : 736
010130. : 736
010620. : 736
010770. : 1100
011000. : 736
011070. : 736
011170. : 736
011200. : 736
011280. : 551
011330. : 5616
011390. : 736
011700. : 736
011810. : 736
011930. : 2749
012330. : 736
012750. : 736
012800. : 489
014280. : 1902
014680. : 736
014990. : 736
016380. : 736
016450. : 551
016590. : 736
016880. : 736
017390. : 736
017550. : 736
017800. : 736
017810. : 736
017900. : 736
017940. : 736
018670. : 736
019180. : 551
019680. : 736
020000. : 736
023530. : 736
025000. : 1534
025620. : 550
028050. : 736
028670. : 736
030000. : 736
030200. : 736
030720. : 736
032640. : 917
033920. : 736
034730. : 736
035000. : 736
035150. : 671
035250. : 736
035720. : 736
036420. : 736
036570. : 736
036580. : 736
037270. : 736
042660. : 736
044380. : 2564
044820. : 736
047050. : 736
049770. : 736
051910. : 736
057050. : 736
058650. : 736
060980. : 736
066570. : 736
068400. : 917
069620. : 736
069640. : 736
071090. : 5616
075180. : 736
077970. : 2749
082740. : 736
085310. : 1534
086280. : 736
088790. : 736
089590. : 2564
092200. : 736
092230. : 736
093050. : 736
096760. : 736
097520. : 736
097950. : 736
101530. : 504
102460. : 4912
109070. : 2749
119650. : 736
120110. : 736
122900. : 736
123690. : 736
128820. : 428
128940. : 736
130660. : 736
136490. : 736
145990. : 736
161390. : 736
163560. : 550
185750. : 5616
192080. : 780
192820. : 736
194370. : 826
204320. : 3068
210980. : 736
213500. : 736
214320. : 736
214330. : 736
227840. : 2564
900140. : 736

In [172]:
len(nan_li)

176

In [147]:
stock_nan_df = pd.read_csv('c:/Users/bitcamp/Desktop/final_data/머신러닝_재무데이터/종목별_511/014680.csv', index_col=0)
stock_nan_df

,date,시가,고가,저가,종가,거래량,거래대금,등락률,종목명,시가총액,...,유동부채,비유동부채,부채총계,이익잉여금,자본총계,매출액,영업이익,법인세차감전 순이익,당기순이익,자본금
0,2016-01-04,62200,63100,59100,59200,59486,3591797600,-4.67,14680,668675544000,...,1.317113e+11,1.653661e+11,2.970775e+11,NaN,2.665161e+11,1.000191e+11,1.984894e+10,2.567010e+10,2.110408e+10,NaN
1,2016-01-05,58000,59800,58000,59000,66616,3924365100,-0.34,14680,666416505000,...,1.317113e+11,1.653661e+11,2.970775e+11,NaN,2.665161e+11,1.000191e+11,1.984894e+10,2.567010e+10,2.110408e+10,NaN
2,2016-01-06,59600,64500,58900,64000,96302,5889894200,8.47,14680,722892480000,...,1.317113e+11,1.653661e+11,2.970775e+11,NaN,2.665161e+11,1.000191e+11,1.984894e+10,2.567010e+10,2.110408e+10,NaN
3,2016-01-07,64000,67500,63400,66600,96462,6374877700,4.06,14680,752259987000,...,1.317113e+11,1.653661e+11,2.970775e+11,NaN,2.665161e+11,1.000191e+11,1.984894e+10,2.567010e+10,2.110408e+10,NaN
4,2016-01-08,66600,67500,64900,65300,57553,3771771800,-1.95,14680,737576233500,...,1.317113e+11,1.653661e+11,2.970775e+11,NaN,2.665161e+11,1.000191e+11,1.984894e+10,2.567010e+10,2.110408e+10,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1529,2022-03-25,230500,236500,228500,235000,92699,21686115000,3.30,14680,2663770825000,...,1.667453e+11,2.328636e+11,3.996089e+11,6.133988e+11,7.872063e+11,2.222281e+11,5.412018e+10,5.809538e+10,4.418548e+10,5.667598e+10
1530,2022-03-28,235000,236000,229000,233000,52734,12307466500,-0.85,14680,2641100435000,...,1.667453e+11,2.328636e+11,3.996089e+11,6.133988e+11,7.872063e+11,2.222281e+11,5.412018e+10,5.809538e+10,4.418548e+10,5.667598e+10
1531,2022-03-29,236000,238500,230000,232500,53985,12641681000,-0.21,14680,2635432837500,...,1.667453e+11,2.328636e+11,3.996089e+11,6.133988e+11,7.872063e+11,2.222281e+11,5.412018e+10,5.809538e+10,4.418548e+10,5.667598e+10
1532,2022-03-30,235500,238500,233000,236000,51695,12172162500,1.51,14680,2675106020000,...,1.667453e+11,2.328636e+11,3.996089e+11,6.133988e+11,7.872063e+11,2.222281e+11,5.412018e+10,5.809538e+10,4.418548e+10,5.667598e+10
1533,2022-03-31,235500,248000,234000,245500,100316,24410413500,4.03,14680,2782790372500,...,1.667453e+11,2.328636e+11,3.996089e+11,6.133988e+11,7.872063e+11,2.222281e+11,5.412018e+10,5.809538e+10,4.418548e+10,5.667598e+10

In [148]:
stock_nan_df.isna().sum()

date            0
시가              0
고가              0
저가              0
종가              0
거래량             0
거래대금            0
등락률             0
종목명             0
시가총액            0
상장주식수           0
수정종가            0
quarter         0
유동자산            0
비유동자산           0
자산총계            0
유동부채            0
비유동부채           0
부채총계            0
이익잉여금         368
자본총계            0
매출액             0
영업이익            0
법인세차감전 순이익      0
당기순이익           0
자본금           368
dtype: int64

In [170]:
stock_nan_df[stock_nan_df['이익잉여금'].isna()]

,date,시가,고가,저가,종가,거래량,거래대금,등락률,종목명,시가총액,...,유동부채,비유동부채,부채총계,이익잉여금,자본총계,매출액,영업이익,법인세차감전 순이익,당기순이익,자본금
0,2016-01-04,62200,63100,59100,59200,59486,3591797600,-4.67,14680,668675544000,...,1.317113e+11,1.653661e+11,2.970775e+11,NaN,2.665161e+11,1.000191e+11,1.984894e+10,2.567010e+10,2.110408e+10,NaN
1,2016-01-05,58000,59800,58000,59000,66616,3924365100,-0.34,14680,666416505000,...,1.317113e+11,1.653661e+11,2.970775e+11,NaN,2.665161e+11,1.000191e+11,1.984894e+10,2.567010e+10,2.110408e+10,NaN
2,2016-01-06,59600,64500,58900,64000,96302,5889894200,8.47,14680,722892480000,...,1.317113e+11,1.653661e+11,2.970775e+11,NaN,2.665161e+11,1.000191e+11,1.984894e+10,2.567010e+10,2.110408e+10,NaN
3,2016-01-07,64000,67500,63400,66600,96462,6374877700,4.06,14680,752259987000,...,1.317113e+11,1.653661e+11,2.970775e+11,NaN,2.665161e+11,1.000191e+11,1.984894e+10,2.567010e+10,2.110408e+10,NaN
4,2016-01-08,66600,67500,64900,65300,57553,3771771800,-1.95,14680,737576233500,...,1.317113e+11,1.653661e+11,2.970775e+11,NaN,2.665161e+11,1.000191e+11,1.984894e+10,2.567010e+10,2.110408e+10,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363,2017-06-26,74000,74000,72100,73000,57682,4196600600,-1.48,14680,824549235000,...,1.733146e+11,2.188253e+11,3.921400e+11,NaN,3.591690e+11,-1.071860e+10,-5.207546e+09,-2.170964e+09,-1.771571e+09,NaN
364,2017-06-27,72500,73600,71800,72200,45901,3319916200,-1.10,14680,815513079000,...,1.733146e+11,2.188253e+11,3.921400e+11,NaN,3.591690e+11,-1.071860e+10,-5.207546e+09,-2.170964e+09,-1.771571e+09,NaN
365,2017-06-28,72300,72300,71000,71400,70265,5021771500,-1.11,14680,806476923000,...,1.733146e+11,2.188253e+11,3.921400e+11,NaN,3.591690e+11,-1.071860e+10,-5.207546e+09,-2.170964e+09,-1.771571e+09,NaN
366,2017-06-29,71600,72000,70400,70400,65016,4593747100,-1.40,14680,795181728000,...,1.733146e+11,2.188253e+11,3.921400e+11,NaN,3.591690e+11,-1.071860e+10,-5.207546e+09,-2.170964e+09,-1.771571e+09,NaN
367,2017-06-30,70100,71600,69800,71000,55902,3948915700,0.85,14680,801958845000,...,1.733146e+11,2.188253e+11,3.921400e+11,NaN,3.591690e+11,-1.071860e+10,-5.207546e+09,-2.170964e+09,-1.771571e+09,NaN

In [169]:
stock_nan_df[stock_nan_df.date < '2016-03-31']['이익잉여금'] = 159835687858

C:\Users\bitcamp\AppData\Local\Temp/ipykernel_14324/3441506112.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_nan_df[stock_nan_df.date < '2016-03-31']['이익잉여금'] = 159835687858

In [155]:
yabal_df = pd.read_excel('c:/Users/bitcamp/Desktop/final_data/재무제표/014680.xlsx')
yabal_df.iloc[48,10:33]

20210930    577006535013
20210630    534366670606
20210331    492072368606
20201231    470804267514
20200930    459232563718
20200630    419313066173
20200331    389740520207
20191231    371778414280
20190930    362183376639
20190630    336036268610
20190331    312005659718
20181231    302700808712
20180930    291847372207
20180630    268859624847
20180331    244365115672
20171231    236752514695
20170930    234195995596
20170630    212093063883
20170331    199024092967
20161231    194613240826
20160930    187837781218
20160630    170235244070
20160331    159835687858
Name: 48, dtype: object

In [ ]:
yabal_df = pd.read_excel('c:/Users/bitcamp/Desktop/final_data/재무제표/000270.xlsx')
yabal_df.iloc[46,28:33]

# 자본금+이익잉여금 버리기

In [180]:
files = os.listdir('c:/Users/bitcamp/Desktop/final_data/머신러닝_재무데이터/종목별_511/')

In [181]:
for file in files:
    df = pd.read_csv(f'c:/Users/bitcamp/Desktop/final_data/머신러닝_재무데이터/종목별_511/{file}', index_col=0)
    df.drop(['자본금', '이익잉여금'], axis=1, inplace=True)
    df.to_csv(f'c:/Users/bitcamp/Desktop/final_data/머신러닝_재무데이터/종목별_511_자본금_이익잉여금_x/{file}')

In [193]:
nan_li = []
for file in files:
    df = pd.read_csv(f'c:/Users/bitcamp/Desktop/final_data/머신러닝_재무데이터/종목별_511_자본금_이익잉여금_x/{file}', index_col=0)
    nan = df.isna().sum().sum()
    if nan > 0:
        print(file[:7]+' : '+str(nan))
        nan_li.append(file)

001790. : 60
002150. : 4048
002620. : 2013
002900. : 60
003850. : 2706
005320. : 60
007460. : 4752
011330. : 4752
011930. : 2013
044380. : 2013
071090. : 4752
077970. : 2013
089590. : 2013
101530. : 432
102460. : 4048
109070. : 2013
185750. : 4752
192080. : 660
194370. : 444
227840. : 2013

In [194]:
len(nan_li)

20

In [192]:
stock_nan_df = pd.read_csv('c:/Users/bitcamp/Desktop/final_data/머신러닝_재무데이터/종목별_511_자본금_이익잉여금_x/007460.csv', index_col=0)
stock_nan_df

,date,시가,고가,저가,종가,거래량,거래대금,등락률,종목명,시가총액,...,비유동자산,자산총계,유동부채,비유동부채,부채총계,자본총계,매출액,영업이익,법인세차감전 순이익,당기순이익
0,2016-01-04,3070,3070,2920,2970,49703,148217520,-1.98,7460,38678209020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-01-05,2885,2990,2870,2945,59743,175017315,-0.84,7460,38352634870,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-01-06,2920,3015,2840,2950,59020,170458285,0.17,7460,38417749700,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-01-07,2945,2945,2770,2825,73170,207136015,-4.24,7460,36789878950,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-01-08,2765,2875,2670,2820,70402,192218755,-0.18,7460,45027018960,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1529,2022-03-25,1500,1525,1475,1485,1741663,2601229815,-1.00,7460,299550640455,...,3.114099e+11,8.230423e+11,1.014683e+11,1.073603e+10,1.122043e+11,7.108380e+11,4.193175e+10,4772965.0,2.495303e+09,226216449.0
1530,2022-03-28,1450,1510,1450,1475,1888395,2797439965,-0.67,7460,297533464425,...,3.114099e+11,8.230423e+11,1.014683e+11,1.073603e+10,1.122043e+11,7.108380e+11,4.193175e+10,4772965.0,2.495303e+09,226216449.0
1531,2022-03-29,1490,1500,1465,1480,1182915,1747407465,0.34,7460,298542052440,...,3.114099e+11,8.230423e+11,1.014683e+11,1.073603e+10,1.122043e+11,7.108380e+11,4.193175e+10,4772965.0,2.495303e+09,226216449.0
1532,2022-03-30,1480,1505,1475,1495,888910,1325511695,1.01,7460,301567816485,...,3.114099e+11,8.230423e+11,1.014683e+11,1.073603e+10,1.122043e+11,7.108380e+11,4.193175e+10,4772965.0,2.495303e+09,226216449.0
1533,2022-03-31,1490,1530,1485,1525,978595,1473205275,2.01,7460,307619344575,...,3.114099e+11,8.230423e+11,1.014683e+11,1.073603e+10,1.122043e+11,7.108380e+11,4.193175e+10,4772965.0,2.495303e+09,226216449.0

# 490개^^

In [197]:
files = os.listdir('c:/Users/bitcamp/Desktop/final_data/머신러닝_재무데이터/종목별_511_자본금_이익잉여금_x_20drop/')
for na in nan_li:
    os.remove(f'c:/Users/bitcamp/Desktop/final_data/머신러닝_재무데이터/종목별_511_자본금_이익잉여금_x_20drop/{na}')

In [195]:
nan_li

['001790.csv',
 '002150.csv',
 '002620.csv',
 '002900.csv',
 '003850.csv',
 '005320.csv',
 '007460.csv',
 '011330.csv',
 '011930.csv',
 '044380.csv',
 '071090.csv',
 '077970.csv',
 '089590.csv',
 '101530.csv',
 '102460.csv',
 '109070.csv',
 '185750.csv',
 '192080.csv',
 '194370.csv',
 '227840.csv']

# last nan값 확인

In [198]:
files = os.listdir('c:/Users/bitcamp/Desktop/final_data/머신러닝_재무데이터/종목별_511_자본금_이익잉여금_x_20drop/')
nan_li = []
for file in files:
    df = pd.read_csv(f'c:/Users/bitcamp/Desktop/final_data/머신러닝_재무데이터/종목별_511_자본금_이익잉여금_x/{file}', index_col=0)
    nan = df.isna().sum().sum()
    if nan > 0:
        print(file[:7]+' : '+str(nan))
        nan_li.append(file)

In [199]:
nan_zero = []
files = os.listdir('c:/Users/bitcamp/Desktop/final_data/머신러닝_재무데이터/종목별_511/')
for file in files:
    df = pd.read_csv(f'c:/Users/bitcamp/Desktop/final_data/머신러닝_재무데이터/종목별_511/{file}', index_col=0)
    if df.isna().sum().sum() == 0:
        df.to_csv(f'c:/Users/bitcamp/Desktop/final_data/머신러닝_재무데이터/종목별_511_자본금_이익잉여금_x_20drop/{file}')
        print(file[:7])
        nan_zero.append(file)

000040.
000080.
000150.
000300.
000390.
000490.
000680.
000700.
000850.
000890.
000950.
000990.
001020.
001040.
001210.
001230.
001460.
001470.
001520.
001800.
001940.
002020.
002030.
002140.
002170.
002220.
002320.
002840.
003000.
003200.
003220.
003300.
003410.
003480.
003490.
003570.
003780.
003960.
004090.
004100.
004270.
004540.
004710.
004770.
004800.
004830.
004870.
004890.
004910.
004960.
004970.
004980.
005010.
005090.
005440.
005720.
005740.
005820.
006120.
006340.
006400.
006570.
006880.
007210.
007310.
007340.
007540.
007610.
007660.
007700.
007980.
008040.
009200.
009540.
009580.
009810.
009970.
010060.
010100.
010600.
010780.
011090.
011230.
011690.
011760.
011780.
011790.
012160.
012170.
012600.
012630.
013360.
013570.
013580.
013870.
014130.
014440.
014530.
014580.
014830.
015260.
015360.
015540.
015760.
015890.
017040.
017370.
017960.
018260.
018880.
020150.
021050.
023150.
023800.
024720.
024890.
024900.
025530.
025560.
026960.
027740.
029530.
031440.
031820.
033240.
033530.
033780.
034120.
036460.
036530.
042670.
044450.
047810.
049800.
053690.
058730.
064350.
064960.
067830.
068270.
069960.
071970.
074610.
075580.
078520.
079550.
081660.
084010.
084670.
090370.
091090.
093370.
094280.
095720.
100250.
105630.
105840.
108670.
111770.
115390.
123700.
129260.
138490.
139480.
183190.
210540.
214420.

In [200]:
len(nan_zero)

167

In [202]:
df_nan_zero = pd.read_csv('c:/Users/bitcamp/Desktop/final_data/머신러닝_재무데이터/종목별_511_자본금_이익잉여금_x_20drop/000040.csv', index_col=0)

In [205]:
df_nan_zero.isna().sum()

date          0
시가            0
고가            0
저가            0
종가            0
거래량           0
거래대금          0
등락률           0
종목명           0
시가총액          0
상장주식수         0
수정종가          0
quarter       0
유동자산          0
비유동자산         0
자산총계          0
유동부채          0
비유동부채         0
부채총계          0
이익잉여금         0
자본총계          0
매출액           0
영업이익          0
법인세차감전 순이익    0
당기순이익         0
자본금           0
dtype: int64