In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings(action='ignore')

import matplotlib as mpl
import matplotlib.font_manager as fm

mpl.rcParams['axes.unicode_minus'] = False

path = 'C:/Windows/Fonts/malgun.ttf'
font_name = fm.FontProperties(fname=path, size=50).get_name()
plt.rc('font', family=font_name)

In [16]:
tt = pd.read_csv('./data_study/소상공인시장진흥공단_상가(상권)정보_서울_202112.csv')
tt.head(2)

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,23324279,제중건강원,NaN,D,소매,D10,건강/미용식품,D10A07,건강원,G47216,...,1156010600100410002034626,NaN,서울특별시 영등포구 영중로14길 11-17,150035,7250.0,NaN,1,NaN,126.907168,37.520613
1,24525909,민속악기사,NaN,D,소매,D04,취미/오락관련소매,D04A09,악기판매,G47593,...,1120012200101420011000227,NaN,서울특별시 성동구 용답5길 2,133849,4803.0,NaN,NaN,NaN,127.049018,37.566857

In [17]:
tt.head(3)

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,23324279,제중건강원,NaN,D,소매,D10,건강/미용식품,D10A07,건강원,G47216,...,1156010600100410002034626,NaN,서울특별시 영등포구 영중로14길 11-17,150035,7250.0,NaN,1,NaN,126.907168,37.520613
1,24525909,민속악기사,NaN,D,소매,D04,취미/오락관련소매,D04A09,악기판매,G47593,...,1120012200101420011000227,NaN,서울특별시 성동구 용답5길 2,133849,4803.0,NaN,NaN,NaN,127.049018,37.566857
2,24715368,태평양진주,NaN,D,소매,D26,시계/귀금속소매,D26A01,시계/귀금속,G47830,...,1111015200100440000000001,금사랑투빌딩,서울특별시 종로구 서순라길 17-10,110390,3138.0,NaN,NaN,NaN,126.993530,37.571848

In [20]:
tt_c=tt.isna().sum()<1000
tt_c

상가업소번호        True
상호명           True
지점명          False
상권업종대분류코드     True
상권업종대분류명      True
상권업종중분류코드     True
상권업종중분류명      True
상권업종소분류코드     True
상권업종소분류명      True
표준산업분류코드     False
표준산업분류명      False
시도코드          True
시도명           True
시군구코드         True
시군구명          True
행정동코드         True
행정동명          True
법정동코드         True
법정동명          True
지번코드          True
대지구분코드        True
대지구분명         True
지번본번지         True
지번부번지        False
지번주소          True
도로명코드         True
도로명           True
건물본번지         True
건물부번지        False
건물관리번호        True
건물명          False
도로명주소         True
구우편번호         True
신우편번호         True
동정보          False
층정보          False
호정보          False
경도            True
위도            True
dtype: bool

In [21]:
tt_cc=tt_c[tt_c].index

In [22]:
tt_cc

Index(['상가업소번호', '상호명', '상권업종대분류코드', '상권업종대분류명', '상권업종중분류코드', '상권업종중분류명',
       '상권업종소분류코드', '상권업종소분류명', '시도코드', '시도명', '시군구코드', '시군구명', '행정동코드',
       '행정동명', '법정동코드', '법정동명', '지번코드', '대지구분코드', '대지구분명', '지번본번지', '지번주소',
       '도로명코드', '도로명', '건물본번지', '건물관리번호', '도로명주소', '구우편번호', '신우편번호', '경도',
       '위도'],
      dtype='object')

In [26]:
tt_11 = tt[tt_cc]

In [27]:
tt_11.isna().sum()

상가업소번호        0
상호명           1
상권업종대분류코드     0
상권업종대분류명      0
상권업종중분류코드     0
상권업종중분류명      0
상권업종소분류코드     0
상권업종소분류명      0
시도코드          0
시도명           0
시군구코드         0
시군구명          0
행정동코드         0
행정동명          5
법정동코드         0
법정동명          0
지번코드          0
대지구분코드        0
대지구분명         0
지번본번지         0
지번주소          0
도로명코드         0
도로명           0
건물본번지         0
건물관리번호        0
도로명주소         0
구우편번호         0
신우편번호        50
경도            0
위도            0
dtype: int64

In [28]:
tt_11.dropna(inplace=True)

In [29]:
tt_11.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 315238 entries, 0 to 315293
Data columns (total 30 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   상가업소번호     315238 non-null  int64
 1   상호명        315238 non-null  object
 2   상권업종대분류코드  315238 non-null  object
 3   상권업종대분류명   315238 non-null  object
 4   상권업종중분류코드  315238 non-null  object
 5   상권업종중분류명   315238 non-null  object
 6   상권업종소분류코드  315238 non-null  object
 7   상권업종소분류명   315238 non-null  object
 8   시도코드       315238 non-null  int64
 9   시도명        315238 non-null  object
 10  시군구코드      315238 non-null  int64
 11  시군구명       315238 non-null  object
 12  행정동코드      315238 non-null  int64
 13  행정동명       315238 non-null  object
 14  법정동코드      315238 non-null  int64
 15  법정동명       315238 non-null  object
 16  지번코드       315238 non-null  int64
 17  대지구분코드     315238 non-null  int64
 18  대지구분명      315238 non-null  object
 19  지번본번지      315238 non-null  int64
 20  지번주소       315238 non-null  object
 21  도로명코드      315238 non-null  int64
 22  도로명        315238 non-null  object
 23  건물본번지      315238 non-null  int64
 24  건물관리번호     315238 non-null  object
 25  도로명주소      315238 non-null  object
 26  구우편번호      315238 non-null  int64
 27  신우편번호      315238 non-null  float64
 28  경도         315238 non-null  float64
 29  위도         315238 non-null  float64
dtypes: float64(3), int64(11), object(16)
memory usage: 74.6+ MB

In [30]:
tt_11.head(2)

,상가업소번호,상호명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,시도코드,시도명,...,지번주소,도로명코드,도로명,건물본번지,건물관리번호,도로명주소,구우편번호,신우편번호,경도,위도
0,23324279,제중건강원,D,소매,D10,건강/미용식품,D10A07,건강원,11,서울특별시,...,서울특별시 영등포구 영등포동5가 41-1,115604154799,서울특별시 영등포구 영중로14길,11,1156010600100410002034626,서울특별시 영등포구 영중로14길 11-17,150035,7250.0,126.907168,37.520613
1,24525909,민속악기사,D,소매,D04,취미/오락관련소매,D04A09,악기판매,11,서울특별시,...,서울특별시 성동구 용답동 142-11,112004109480,서울특별시 성동구 용답5길,2,1120012200101420011000227,서울특별시 성동구 용답5길 2,133849,4803.0,127.049018,37.566857

In [31]:
tt_11['상호명']=tt_11['상호명'].apply(lambda x:x.lower())

In [32]:
tt31 = tt_11[tt_11['상호명'].str.contains('(베|배)스킨라빈스|baskinrobbins')]

In [35]:
tt31.상호명.unique()

array(['배스킨라빈스공릉점', '배스킨라빈스강남중앙', '배스킨라빈스31', '배스킨라빈스31상봉역점',
       '배스킨라빈스31서초점', '배스킨라빈스31응암역점', '배스킨라빈스31반포삼호가든점', '배스킨라빈스31오금역점',
       '배스킨라빈스31신정네거리점', '배스킨라빈스31중계점', '배스킨라빈스', '배스킨라빈스31미아역점',
       '배스킨라빈스31신림점', '배스킨라빈스31영등포구청점', '베스킨라빈스신림포도몰', '베스킨라빈스송파',
       '배스킨라빈스31난곡점', '배스킨라빈스31망우우림점', '베스킨라빈스마들역점', '배스킨라빈스31신당점',
       '배스킨라빈스서울베이비키즈페어임시부스', '베스킨라빈스', '배스킨라빈스31개봉중앙점',
       '배스킨라빈스31남부터미널역점', '배스킨라빈스31북가좌점', '배스킨라빈스31신정점', '배스킨라빈스31방배역점',
       '배스킨라빈스31응암2호점', '배스킨라빈스31금천홈플러스점', '배스킨라빈스31포이점', '배스킨라빈스31전농동아점',
       '배스킨라빈스31청담2호점', '배스킨라빈스31중계은행점', '배스킨라빈스31이태원점',
       '배스킨라빈스31신내홈플러스점', '배스킨라빈스31노량진점', '배스킨라빈스31은평뉴타운점', '배스킨라빈스31응암점',
       '배스킨라빈스31망원역점', '배스킨라빈스31양재매헌점', '배스킨라빈스31까치산역점', '배스킨라빈스31구의역점',
       '베스킨라빈스신도림테크노마트', '배스킨라빈스31이수역점', '배스킨라빈스31연신내점', '배스킨라빈스31수락산역점',
       '배스킨라빈스31남구로점', '배스킨라빈스31쌍문점', '배스킨라빈스31상암홈플러스점', '배스킨라빈스31구로고척점',
       '용산역이마트배스킨라빈스', '배스킨라빈스31안암점', '배스킨라빈스31아차산역점', '배스킨라빈스31방화동점',
       '배스킨라빈스31cafe31신촌점', '배스킨라빈스31둔촌역점', '배스킨라빈스31중랑구청점',
       '베스킨라빈스월계이마트', '배스킨라빈스31동묘역점', '배스킨라빈스31건대역점', '배스킨라빈스31둔촌푸르지오점',
       '배스킨라빈스신방화역점', '배스킨라빈스31한양대점', '배스킨라빈스31중곡역점', '배스킨라빈스31광운대역점',
       '써티원베스킨라빈스', '배스킨라빈스31명일역점', '배스킨라빈스31도화점', '배스킨라빈스31당산역점',
       '배스킨라빈스성동금호점', '배스킨라빈스31면목역점', '베스킨라빈스남부터미널역점', '배스킨라빈스31신도림홈플러스점',
       '배스킨라빈스31개봉푸르지오점', '배스킨라빈스31중앙대점', '배스킨라빈스31방학역점', '베스킨라빈스은행나무점',
       '배스킨라빈스위례아이파크점', '배스킨라빈스31굽은다리역점', '배스킨라빈스31중랑역점', '베스킨라빈스아이스크림',
       '배스킨라빈스31서울숲점', '베스킨라빈스가락본동점', '배스킨라빈스동대문홈플러스', '배스킨라빈스교대점',
       '베스킨라빈스목동2단지점', '배스킨라빈스신풍역', '베스킨라빈스롯데몰', '배스킨라빈스31선유도역',
       '배스킨라빈스31마포용강점', '배스킨라빈스31홍은동점', '배스킨라빈스31신도림테크노마트점',
       '배스킨라빈스31미아삼거리점', '배스킨라빈스31선릉점', '배스킨라빈스31안국역점', '배스킨라빈스31화양삼거리점',
       '배스킨라빈스31보라매공원점', '배스킨라빈스31수색이마트점', '배스킨라빈스31월곡홈플러스점',
       '배스킨라빈스31길음뉴타운점', '배스킨라빈스31성신여대점', '배스킨라빈스31성수이마트점',
       '배스킨라빈스31홍대상상마당점', '배스킨라빈스31답십리역점', '배스킨라빈스31강서구청점',
       '배스킨라빈스31서울대입구역점', '배스킨라빈스31한성대입구역점', '베스킨라빈스삼전점', '배스킨라빈스31구로구청점',
       '비알코리아베스킨라빈스양', '배스킨라빈스31대림성모점', '배스킨라빈스31숙명여대점', '베스킨라빈스성수역점',
       '베스킨라빈스강남', '배스킨라빈스31구로오류동', '배스킨라빈스방이역점', '배스킨라빈스31신월신곡점',
       '베스킨라빈스이마트점', '베스킨라빈스쌍문점', '베스킨라빈스중계은행', '베스킨라빈스31아이스크림',
       '배스킨라빈스노원세이브존', '베스킨라빈스장안점', '베스킨라빈스신월', '배스킨라빈스남성역점',
       '배스킨라빈스브라운청담점', '배스킨라빈스청량리역사점', '베스킨라빈스미아역점', '베스킨라빈스중곡역',
       '배스킨라빈스서울역2호'], dtype=object)